### ISSUE TITLE
Button class removed in mobile mode (action button not working properly)

### ISSUE THREAD

**Issue by TTorgersen** [johndatserakis/vue-navigation-bar#16]
The logout button works fine in full screen mode, but when I reduce the screen the navbar collapses. In this collapsed mode the logout button is missing its class tag, and does not redirect the user . 

This is the navbarOptions and menuOptionsRight:

```javascript
 navbarOptions: {
        elementId: "main-navbar",  
        isUsingVueRouter: true,   
        mobileBreakpoint: 992,
        brandImagePath: "./",
        brandImage: require("../assets/windtech.png"),
        brandImageAltText: "brand-image",
        collapseButtonImageOpen: require("../assets/bars.png"),
        collapseButtonImageClose: require("../assets/times.png"),
        showBrandImageInMobilePopup: true,
        ariaLabelMainNav: "Main Navigation",
        tooltipAnimationType: "shift-away",
        menuOptionsLeft: [
  ...
        ],
        menuOptionsRight: [
          {
            type: "button",
            text: "Log out",
            path: "./",
            class: "logoutBtn",
            iconRight:
             <svg id="i-arrow-right" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"> <path d="M22 6 L30 16 22 26 M30 16 L2 16" /> </svg>,
          },
        ],
```

Using this method to fetch the button and add onclick event: 

```javascript
let logout = document.querySelector(".logoutBtn");
logout.onclick = async function signOut() {
```

The error message logged is : (Promise/async): "TypeError: Cannot set property 'onclick' of null"

**Comment by johndatserakis** [comment]
Hi there @TTorgersen - sorry you're having issues.

Hmm, I see what you're saying. I just merged in a [PR](https://github.com/johndatserakis/vue-navigation-bar/pull/17) that addresses this.

The reason I had it set up the way I did is because, on the `Popup`, all those items are actually links - not buttons. This is to fit the smaller `Popup` style. In that way, I didn't want a custom class that may be added to a `button` to cause too much of a styling problem when applied to a `link`.

So, going forward, make sure to adjust your custom styling to consider the mobile view if needed - perhaps by using a media query like I do in the revised example - `@media (min-width: 992px) { ... }`, to make sure the styles you want only apply to the desktop version (but you'll now still have the class there of course).

I will say, that this library actually already has a way to trigger actions on the click of a button/link - the `isLinkAction` property. You can see an example in the demo app by clicking the `About` menu option. The example app is in the `./example` folder. 

What the `isLinkAction` does is `$emit` an event that lets you filter for which menu item was clicked, and then do something with that menu click. I would honestly consider using that method, as you're kind mixing raw `JavaScript` with `Vue` in your example and I've found that can lead to headaches in the future. Just my 2 cents.

Thank you.

**Comment by TTorgersen** [comment]
Thank you @johndatserakis for the thorough feedback on my issue!

**Comment by TTorgersen** [comment]
Hi again @johndatserakis , with the help of your comment it worked out! The method we used to logout did not properly redirect the user with the `type: "link"`, so what we had to implement in addition was a history mode push as such: `this.$router.push('/')`.
Thanks for your help!

**Comment by johndatserakis** [comment]
Awesome - glad you got it working.
