### ISSUE TITLE
New vue-router Logic Breaks NuxtJS automated route configuration

### ISSUE THREAD

**Issue by SomethingNew71** [johndatserakis/vue-navigation-bar#19]
Hey John,

Was just updating my app with the new 4.x version of the navbar and it's broken the way NuxtJS configures its routes. The way you have it set up its effectively requiring the user of the component to use `named routes` While it probably would work for whoever is installing this with a manually configured vue-router, if this is used with NuxtJS it breaks as NuxtJS generates the routes based on the directory structure. 

I am gonna work up a small PR that I think should resolve it with an additional option to choose between `path` routes or `named-routes`.

Named Routes Reference: https://router.vuejs.org/guide/essentials/named-routes.html

**Comment by johndatserakis** [comment]
Hey Cole - sorry about that. I was planning on gauging the interest/need for an alternate route type after this move, and it seems like that need was instant, ha. I just merged your pr.

I'd like to discuss this with you though really quick - I have this question on the change you made: https://github.com/johndatserakis/vue-navigation-bar/pull/20/files#r456973607.

I think it needs to be `{ props: { to: { path: this.path.path } } }` instead of `{ props: { to: { path: this.path } } }` on this line in the `else` block. The reason being, is that when using `vue-router` I think it's a minimum requirement of providing the `path` property - so this will allow that to work. The first `path` property in the code here is actually the `path` for the menu-item - I think that what's confusing.

Edit - you know what - after looking at it a little further, I think it's fine to leave it like you have it. I'll just update the `README` to explain the prop like this:

- menuOptionsLeft.path
- String or Object 
- Link path of menu-option. If you have `isUsingVueRouter === true`, then this needs to be an `Object` with a `name` property or just a `String` of your path. Otherwise, just provide a `String`. Not applicable to `dropdown` menuOption types.

What I'll do is put this in the `README` now, and then we'll decide if we just leave it how you have it - which I'm actually cool with at this point.

Let me know what you think.

**Comment by SomethingNew71** [comment]
Hey John,

I see what you were thinking, but I don't think the rework is necessary. The only time you would need to do `this.path.path` is if the method of passing the path along always needed to be an object. When I set it up I basically assumed if the developer was not passing an object and it was only a string it would only pass the path along. I think that feels like the right route to take in your docs. Gives them the choice to do either without any extra configuration. I also tested it in my Nuxt app and it worked. 👍

**Comment by johndatserakis** [comment]
Ok awesome yup I totally agree. Thanks for the quick fix!

**Comment by SomethingNew71** [comment]
Super happy to help! When do you think a release will be created with the fix in it? I can't update past 4.0.0 until its in there and 4+ is broken for nuxt users currently.

**Comment by johndatserakis** [comment]
Hey Cole - is the current `v4.0.2` not working for you? I had already pushed a new version with your fix in there.

**Comment by SomethingNew71** [comment]
Oh whoops I totally missed the 4.0.2 release 🤦 It totally works thank you.

**Comment by johndatserakis** [comment]
No sweat!
