### ISSUE TITLE
Html in text of link?

### ISSUE THREAD

**Issue by jeffreykthomas** [johndatserakis/vue-navigation-bar#21]
Is it currently possible to add styles somehow to the text of a link?

So something like:

```
{
  type: 'link',
  text: 'Our <span style="color: #be0726">System</span>',
...
}
```

Thanks in advance!

**Comment by johndatserakis** [comment]
Hmm, no sorry at this moment the custom `class` is only applied to buttons. I will consider adding the custom `class` to links coming up - it's just tougher with links in the initial design because of how the styling is handled in the menu.

If you'd like to target all the links, you can use the `vnb__menu-options__option__link` or `vnb__sub-menu-options__option__link` selector to color them. Also, you could take a look at the actual `vue-navigation-bar` instance using `$refs` to access the instance, although that's a bit hacky for this use case.

If I get a block of time to add this, and make sure not to break any other parts of the menu, I'll update here when complete. Thank you.

**Comment by meyer744** [comment]
Somewhat related... Is it possible to include an @click="myFunction" with the button to fire a method?

**Comment by johndatserakis** [comment]
Hey there @meyer744, for reacting to button clicks you can listen for the `vnb-item-clicked` event and then match the `text` value of the passed param. An example of this is here: https://github.com/johndatserakis/vue-navigation-bar/blob/af05628d906eb0c18aeb44336d1537b447cba702/example/App.vue#L208 in the demo application. Let me know if I can help further.

**Comment by billyriantono** [comment]
hi @johndatserakis how to hide the menu in certain condition , like after user login hide the login / signup to be logout.

Thank you

**Comment by johndatserakis** [comment]
Hey @billyriantono - sure, to do that you can dynamically adjust your `options` based on the current state of the user. I do that and return the result as a computed variable in my open-source project [here](https://github.com/johndatserakis/koa-vue-notes-web/blob/develop/src/components/partials/main/Navbar.vue#L40), for example. Some version of this should do you just fine.

**Comment by billyriantono** [comment]
hi @johndatserakis thank you for the guidance :D it's works now :)
