### ISSUE TITLE
Please update it to Latest Vuejs v3 + TypeScript

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [johndatserakis/vue-navigation-bar#25]
Please update it to Latest Vuejs v3 + TypeScript

**Comment by jeffreykthomas** [comment]
Any plans in the works to update for Vue 3?

**Comment by madebylydia** [comment]
@johndatserakis Is the project... dead? It appears so. If so it would be nice to include a notice in your README.md in order to let developers to not use this component Vue 3.

**Comment by johndatserakis** [comment]
Hi there - sorry this component hasn't been updated to support Vue 3 yet (or TypeScript).

In the coming weeks I will research what it takes for this component to be more compatible with Vue 3. I personally haven't moved to Vue 3 yet in my personal projects due to some third-party components not being compatible (like this one ha), but I think I need to look into more to get a better idea.

**Comment by madebylydia** [comment]
Hi there, thank you for the kind update even if my comment was a bit rude. It is nice to know that you will try your best to make this component usable by Vue 3. Hope to hear more from you soon!

**Comment by johndatserakis** [comment]
All good - honestly I think you had a good point about putting something in the README that indicates that this project is not Vue 3 ready yet.

Because of the size of the project, and because I am using more React now than Vue, I do not feel I could move this to Vue 3 without some focused work. Unfortunately I've been extremely busy over the past year and I wouldn't know exactly when I would have time to do this. Additionally, I have converted some other Vue project to TypeScript, and honestly it was less than ideal. I hear the support is better in Vue 3, but I'd have to learn the intricacies better before doing that.

So for now, I'll update the README and hope to get to this at some point. I'm sorry this is unbecoming of a proper library and I'm not happy that I cannot upgrade it to Vue 3 right at this moment. When I do have time, can't say when, I will do it. It's just tough right now. Thank you.

Edit: I'm updating the README right now and that will show up shortly.

**Comment by johndatserakis** [comment]
`vue-navigation-bar` has been upgrade to support Vue 3 via this [PR](https://github.com/johndatserakis/vue-navigation-bar/pull/31). Vue 3 is supported from `v5.0.0` and beyond (current master). To use `vue-navigation-bar` with Vue 2, use `v4.1.0`.

I'm not sure TypeScript will be added to this component, as many things have changed since I have written it. The scope would perhaps be too large. I may take a crack at it one day, but I'd be open to PR's adding at the very least basic types.

Thank you for your patience.
