### ISSUE TITLE
isLinkAction doesn't prevent the navigation to path.name

### ISSUE THREAD

**Issue by erusso7** [johndatserakis/vue-navigation-bar#34]
Hello, 

I'm trying to use the `isLinkAction: true` option, and what I see is that it's triggering the event as expected but then it's navigating to the route defined with the **required** property `path.name`. Also, I've checked the [demo page](https://johndatserakis.github.io/) and it's working the same way

**Documentation says:**
> Sometimes you may want your links to perform an action instead of following a link. To do this, add the isLinkAction property to your menuOption and it'll emit the vnb-item-clicked event with the text property of the menuOption . This will suppress the path option so the link no longer goes anywhere, but instead just sends the event. Checkout the example page to see this in action.

**So me questions are:** 
- Is this a know issue? 
- Is there any workaround to prevent this? 

Alternatives:
- Do not make `path.name` a required property.
- Not only emit the `menuOption.text` value to the event handler function, but instead send the `event` and it can be prevented from outside with `event.preventDefault()`

Thanks

**Comment by johndatserakis** [comment]
Hey there - yes I see that the About link is still navigating after the event is fired. This bug was most likely introduced in my recent reworking for Vue3. Thanks for pointing it out.

I am swamped - I will try to fix this asap. For now, could you put `#` as your `path.name` value? That will at least not actually navigate anywhere.
